# Generated by Django 5.0.6 on 2024-06-03 01:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_farmacia', '0002_rename_nome_cliente_cliente_cpf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=250, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=250, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='idProduto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_farmacia.produto', verbose_name='Código do Produto'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='qtdMinima',
            field=models.IntegerField(verbose_name='Quantidade Mínima'),
        ),
        migrations.AlterField(
            model_name='estoque',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cargo',
            field=models.CharField(max_length=250, verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='cpf',
            field=models.CharField(max_length=250, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dataAdmissao',
            field=models.DateField(verbose_name='Data de Admissão'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='dataNasc',
            field=models.DateField(verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='email',
            field=models.CharField(max_length=250, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='endereco',
            field=models.CharField(max_length=250, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='salario',
            field=models.FloatField(verbose_name='Salário'),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='telefone',
            field=models.CharField(max_length=250, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='categoria',
            field=models.CharField(max_length=250, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='dataValidade',
            field=models.DateField(verbose_name='Data de Validade'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.CharField(max_length=500, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='emailFornecedor',
            field=models.CharField(max_length=250, verbose_name='E-mail do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(max_length=250, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nomeForncedor',
            field=models.CharField(max_length=250, verbose_name='Nome do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='prescricao',
            field=models.BooleanField(verbose_name='Prescrição'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='idFuncionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_farmacia.funcionario', verbose_name='Código do Funcionário'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='itens',
            field=models.CharField(max_length=1000, verbose_name='Itens da Venda'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='nomeCliente',
            field=models.CharField(max_length=250, verbose_name='Nome do Cliente'),
        ),
    ]
