# Generated by Django 5.0.6 on 2024-06-03 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_farmacia', '0003_alter_cliente_cpf_alter_cliente_nome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='preco',
            field=models.FloatField(verbose_name='Preço'),
        ),
    ]
