# Generated by Django 5.0.6 on 2024-06-03 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_farmacia', '0004_alter_produto_preco'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='emailFornecedor',
            field=models.CharField(max_length=250, null=True, verbose_name='E-mail do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nomeForncedor',
            field=models.CharField(max_length=250, null=True, verbose_name='Nome do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='prescricao',
            field=models.BooleanField(null=True, verbose_name='Prescrição'),
        ),
    ]
