# Generated by Django 5.0.6 on 2024-06-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_farmacia', '0005_alter_produto_emailfornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='qtdMinima',
            field=models.IntegerField(null=True, verbose_name='Quantidade Mínima'),
        ),
    ]
